/*global angular */

/**
 * @ngdoc function
 * @name ngResearchApp.service:editorModels
 * @description
 * # EditorModelsService
 * Service that returns the models generated by LabVIEW
 */

angular.module('ngResearchApp').factory('editorModels', function () {
    'use strict';
    var editorModels = {
        gauge1: {
            ranges: [{ startValue: 0, endValue: 55, style: { fill: '#4bb648', stroke: '#4bb648' }, endWidth: 5, startWidth: 5 },
                     { startValue: 25, endValue: 50, style: { fill: '#fbd109', stroke: '#fbd109' }, endWidth: 10, startWidth: 5 },
                         { startValue: 50, endValue: 85, style: { fill: '#ff8000', stroke: '#ff8000' }, endWidth: 13, startWidth: 10 },
                         { startValue: 85, endValue: 100, style: { fill: '#e02629', stroke: '#e02629' }, endWidth: 16, startWidth: 13}],
            ticksMinor: { interval: 5, size: '5%' },
            ticksMajor: { interval: 10, size: '9%' },
            value: 60,
            min: 0,
            max: 100,
            animationDuration: 100
        },
        gauge2: {
            min: 0,
            max: 250,
            value: 0,
            animationDuration: 500
        },
        slider1: {
            min: 0,
            max: 1000,
            ticksFrequency: 100,
            value: 1000,
            step: 5
        },
        numeric1: {
            width: '250px',
            height: '25px',
            spinButtons: true
        }
    };
    return editorModels;
});